version: "3.7"
services:
  bot:
    image: cryptobot
    container_name: crypto_bot
    build:
      context: .
    command: ['python', 'main.py']
    env_file:
      - .env
    depends_on:
      - database_psql

  database_psql:
    container_name: psql_database
    image: postgres:15
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure


volumes:
  pgdata:
