version: "3.7"
services:
  bot:
    image: cryptobot
    container_name: crypto_bot
    build:
      context: .
    command: ['python', 'main.py']
    env_file:
      - .env
    depends_on:
      - database_psql

  database_psql:
    container_name: psql_database
    image: postgres:15
    ports:
      - '5433:5433'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure


volumes:
  pgdata:
